# Generated by Django 3.2.9 on 2021-11-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=2)),
                ('altura', models.FloatField(blank=True, default=None, null=True)),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('nascimento', models.DateTimeField(null=True, verbose_name='Data de Nascimento')),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('numero', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
